import assert from 'node:assert/strict';
import { test } from 'node:test';
import { agentsDocs, renderIssueTrackerDoc, renderTriageLabelsDoc } from '../src/core/agents-docs.js';
import { githubAssignArgs } from '../src/core/tracker/github.js';
import { registerTracker, startTicket } from '../src/core/tracker/index.js';
import { resolveJiraCredentials } from '../src/core/tracker/jira.js';

test('resolveJiraCredentials: process env wins, file fills the gaps, config baseUrl wins over both', () => {
  const file = 'JIRA_URL="https://acme.atlassian.net/"\nexport JIRA_EMAIL=me@acme.test\nJIRA_API_TOKEN=\'tok\'\n';
  assert.deepEqual(resolveJiraCredentials({}, file, null), { email: 'me@acme.test', token: 'tok', baseUrl: 'https://acme.atlassian.net' });
  assert.deepEqual(resolveJiraCredentials({ JIRA_EMAIL: 'env@acme.test' }, file, 'https://cfg.atlassian.net'), {
    email: 'env@acme.test',
    token: 'tok',
    baseUrl: 'https://cfg.atlassian.net',
  });
  assert.deepEqual(resolveJiraCredentials({}, null, null), { email: null, token: null, baseUrl: null });
});

test('githubAssignArgs targets the base repo when known', () => {
  assert.deepEqual(githubAssignArgs(12, null), ['issue', 'edit', '12', '--add-assignee', '@me']);
  assert.deepEqual(githubAssignArgs(12, 'https://github.com/o/r.git'), ['issue', 'edit', '12', '--add-assignee', '@me', '--repo', 'https://github.com/o/r.git']);
});

test('startTicket: no ticket in the branch → null; adapter errors become notes, never throws', async () => {
  const notes = [];
  const note = (m) => notes.push(m);
  assert.equal(await startTicket({ branch: 'feature/no-ticket', tracker: { kind: 'jira', project: 'DAZ' }, note }), null);
  registerTracker('boom', {
    startTicket: async () => {
      throw new Error('kaboom');
    },
  });
  assert.equal(await startTicket({ branch: 'X-7-Thing', tracker: { kind: 'boom', prefix: 'X' }, note }), null, 'unknown kind has no ticket pattern');
  const calls = [];
  registerTracker('jira', { startTicket: async (args) => calls.push(args.key) });
  assert.equal(await startTicket({ branch: 'DAZ-42-FE-Thing', tracker: { kind: 'jira', project: 'DAZ' }, note, log: () => {} }), 'DAZ-42');
  assert.deepEqual(calls, ['DAZ-42']);
  registerTracker('github', {
    startTicket: async () => {
      throw new Error('kaboom');
    },
  });
  assert.equal(await startTicket({ branch: 'GH-9-Adapters', tracker: { kind: 'github', prefix: 'GH' }, note, log: () => {} }), 'GH-9');
  assert.match(notes.at(-1), /github: kaboom — start GH-9 by hand/);
});

test('docs/agents renderers carry the tracker specifics and the generated header', () => {
  const jira = renderIssueTrackerDoc({ kind: 'jira', project: 'DAZ', baseUrl: 'https://inventorie.atlassian.net' });
  assert.match(jira, /^<!-- Generated by @coding-with-hassan\/devkit/);
  assert.match(jira, /Jira project \*\*DAZ\*\* at https:\/\/inventorie\.atlassian\.net/);
  assert.match(jira, /hassan-devkit worktree:create DAZ-<n>-/);
  assert.match(jira, /Never try to delete issues/);
  const gh = renderIssueTrackerDoc({ kind: 'github', prefix: 'GH' });
  assert.match(gh, /branch `GH-<n>-Short-Title`/);
  assert.match(gh, /Closes #<n>/);
  assert.match(gh, /gh issue edit <n> --add-assignee @me/);
  const none = renderIssueTrackerDoc({ kind: 'none' });
  assert.match(none, /none configured/);
  assert.match(renderTriageLabelsDoc(), /\| `ready-for-agent` \| `ready-for-agent` \|/);
  assert.deepEqual(
    agentsDocs({ kind: 'none' }).map(([p]) => p),
    ['docs/agents/issue-tracker.md', 'docs/agents/triage-labels.md', 'docs/agents/domain.md'],
  );
});
