/**
 * `docs/agents/*.md` — the repo-local adapters the engineering skills read ("publish to
 * the issue tracker", "apply the AFK-ready label", "read the domain docs"). Rendered from
 * the tracker config so the endpoints and vocabulary can never drift from what
 * `worktree:create` actually does. Regenerated by `hassan-devkit init`.
 */

export const GENERATED_HEADER = (source) =>
  `<!-- Generated by @coding-with-hassan/devkit from ${source} — edit package.json and re-run \`hassan-devkit init\`; do not edit by hand. -->\n\n`;

export const TRIAGE_LABELS = [
  ['needs-triage', 'Maintainer needs to evaluate this issue'],
  ['needs-info', 'Waiting on reporter for more information'],
  ['ready-for-agent', 'Fully specified, ready for an AFK agent'],
  ['ready-for-human', 'Requires human implementation'],
  ['wontfix', 'Will not be actioned'],
];

export function renderIssueTrackerDoc(tracker) {
  const head = GENERATED_HEADER('the "hassan-devkit.tracker" config');
  if (tracker.kind === 'jira') return head + jiraDoc(tracker);
  if (tracker.kind === 'github') return head + githubDoc(tracker);
  return (
    head +
    `# Issue tracker: none configured

This repo has no issue tracker wired into the devkit (\`hassan-devkit.tracker.kind\` is \`none\`).
When a skill says "publish to the issue tracker" or "fetch the relevant ticket", ask the user
where the work is tracked instead of inventing a destination. Branch names carry no ticket
token and commit subjects need none.
`
  );
}

function jiraDoc({ project, baseUrl }) {
  const site = baseUrl ?? 'the Jira site from `JIRA_URL` in `~/.config/jira/env`';
  const k = `${project}-<n>`;
  return `# Issue tracker: Jira (${project})

Issues and specs for this repo live in the Jira project **${project}** at ${site}. Use the
Atlassian MCP tools when connected (createJiraIssue, getJiraIssue, searchJiraIssuesUsingJql,
editJiraIssue, addCommentToJiraIssue, transitionJiraIssue); fall back to the REST API with
\`curl\` using the credentials in \`~/.config/jira/env\` (JIRA_URL, JIRA_EMAIL, JIRA_API_TOKEN —
basic auth).

## Issue types

- **Task** — technical work (refactors, infra, chores)
- **New Feature** — net-new functionality
- **Story** — changes to existing behavior

Pick the type by this rule, not by gut feel.

## Conventions

- **Branches and commits** carry the ticket key: branch \`${project}-<n>-Short-Title\`, commit
  subject \`${project}-<n> type(scope): …\` (see \`hassan-devkit commits:show\`).
- **Create an issue**: MCP \`createJiraIssue\` with projectKey \`${project}\`, or \`POST /rest/api/3/issue\`.
- **Read an issue**: MCP \`getJiraIssue\` (include comments), or
  \`GET /rest/api/3/issue/${k}?expand=renderedFields\` + \`GET /rest/api/3/issue/${k}/comment\`.
- **List issues**: MCP \`searchJiraIssuesUsingJql\`, e.g.
  \`project = ${project} AND statusCategory != Done ORDER BY created DESC\`.
- **Comment**: MCP \`addCommentToJiraIssue\`, or \`POST .../comment\`.
- **Assign — always to the current user when you start a ticket**: whoever starts the work
  owns the issue. \`hassan-devkit worktree:create ${project}-<n>-…\` does it for the branch's
  ticket (alongside the To Do → In Progress transition); for any other way of picking up a
  ticket, do it yourself first: MCP \`editJiraIssue\` on the \`assignee\` field, or
  \`GET /rest/api/3/myself\` for your \`accountId\` and \`PUT /rest/api/3/issue/${k}/assignee\`
  with \`{"accountId": "<id>"}\`. Never leave a ticket you are working on unassigned or
  assigned to someone else.
- **Labels**: set via \`editJiraIssue\` on the \`labels\` field (add/remove by updating the array).
- **Close**: MCP \`transitionJiraIssue\` — fetch available transitions first with
  \`getTransitionsForJiraIssue\`; the workflow decides valid target states.
- **Never try to delete issues** — the Jira Free plan doesn't allow it. Close/transition instead.

## When a skill says "publish to the issue tracker"

Create a Jira issue in ${project} (choose the issue type per the table above).

## When a skill says "fetch the relevant ticket"

Fetch the ${project} issue with its comments.

## Wayfinding operations

The **map** is a single ${project} issue labelled \`wayfinder-map\`; child tickets are issues
linked to it ("relates to" or parent link where available) with a \`Part of ${k}\` line at the
top of the description and a \`wayfinder-<type>\` label (\`research\`/\`prototype\`/\`grilling\`/\`task\`).
Blocking uses Jira's native "is blocked by" issue links. Claim = assign to yourself;
resolve = comment with the answer, then transition to Done.
`;
}

function githubDoc({ prefix }) {
  return `# Issue tracker: GitHub Issues

Issues and specs for this repo live in GitHub Issues of the **base repository** (the
\`upstream\` remote in the fork model, else \`origin\`). Use the \`gh\` CLI; it is authenticated on
this machine.

## Conventions

- **Branches and commits** carry the issue as \`${prefix}-<n>\`: branch \`${prefix}-<n>-Short-Title\`,
  commit subject \`${prefix}-<n> type(scope): …\` (see \`hassan-devkit commits:show\`). A leading
  \`#<n>\` is never used in a subject — git treats \`#\` lines as comments in the editor.
- **PR body** ends with \`Closes #<n>\` so the issue closes on merge.
- **Create an issue**: \`gh issue create --repo <owner/repo> --title … --body …\`.
- **Read an issue**: \`gh issue view <n> --comments\`.
- **List issues**: \`gh issue list --state open\` (add \`--label\` / \`--assignee @me\` as needed).
- **Comment**: \`gh issue comment <n> --body …\`.
- **Assign — always to the current user when you start an issue**: whoever starts the work
  owns it. \`hassan-devkit worktree:create ${prefix}-<n>-…\` runs \`gh issue edit <n> --add-assignee @me\`
  for the branch's issue; for any other way of picking up an issue, run that yourself first.
  There is no status field: an open PR is the progress signal.
- **Labels**: \`gh issue edit <n> --add-label … / --remove-label …\`.
- **Close**: \`gh issue close <n>\` (or let the PR's \`Closes #<n>\` do it).

## When a skill says "publish to the issue tracker"

Create a GitHub issue on the base repository.

## When a skill says "fetch the relevant ticket"

Fetch the issue with its comments (\`gh issue view <n> --comments\`).

## Wayfinding operations

The **map** is a single issue labelled \`wayfinder-map\`; child issues carry a \`Part of #<map>\`
line at the top of the body and a \`wayfinder-<type>\` label (\`research\`/\`prototype\`/\`grilling\`/\`task\`).
Blocking is a \`Blocked by #<n>\` line in the body (GitHub has no native blocking link outside
Projects). Claim = assign to yourself; resolve = comment with the answer, then close.
`;
}

export function renderTriageLabelsDoc() {
  const rows = TRIAGE_LABELS.map(([label, meaning]) => `| \`${label}\` | \`${label}\` | ${meaning} |`).join('\n');
  return `${GENERATED_HEADER('the devkit triage vocabulary')}# Triage Labels

The skills speak in terms of five canonical triage roles. This file maps those roles to the
label strings used in this repo's issue tracker — identical by convention, so a label travels
unchanged between repos.

| Label in mattpocock/skills | Label in our tracker | Meaning |
| --- | --- | --- |
${rows}

When a skill mentions a role (e.g. "apply the AFK-ready triage label"), use the corresponding
label string from this table.
`;
}

export function renderDomainDoc() {
  return `${GENERATED_HEADER('the devkit domain-docs convention')}# Domain Docs

How the engineering skills should consume this repo's domain documentation when exploring
the codebase.

## Before exploring, read these

- **\`CONTEXT.md\`** at the repo root, or
- **\`CONTEXT-MAP.md\`** at the repo root if it exists — it points at one \`CONTEXT.md\` per
  context. Read each one relevant to the topic.
- **\`docs/adr/\`** — read ADRs that touch the area you're about to work in. In multi-context
  repos, also check \`src/<context>/docs/adr/\` for context-scoped decisions.

If any of these files don't exist, **proceed silently**. Don't flag their absence; don't
suggest creating them upfront. The \`/domain-modeling\` skill (reached via \`/grill-with-docs\`
and \`/improve-codebase-architecture\`) creates them lazily when terms or decisions actually
get resolved.

## File structure

Single-context repo (most repos):

\`\`\`
/
├── CONTEXT.md
├── docs/adr/
│   ├── 0001-event-sourced-orders.md
│   └── 0002-postgres-for-write-model.md
└── src/
\`\`\`

Multi-context repo (presence of \`CONTEXT-MAP.md\` at the root):

\`\`\`
/
├── CONTEXT-MAP.md
├── docs/adr/                          ← system-wide decisions
└── src/
    ├── ordering/
    │   ├── CONTEXT.md
    │   └── docs/adr/                  ← context-specific decisions
    └── billing/
        ├── CONTEXT.md
        └── docs/adr/
\`\`\`

## Use the glossary's vocabulary

When your output names a domain concept (in an issue title, a refactor proposal, a
hypothesis, a test name), use the term as defined in \`CONTEXT.md\`. Don't drift to synonyms
the glossary explicitly avoids.

If the concept you need isn't in the glossary yet, that's a signal — either you're inventing
language the project doesn't use (reconsider) or there's a real gap (note it for
\`/domain-modeling\`).

## Flag ADR conflicts

If your output contradicts an existing ADR, surface it explicitly rather than silently
overriding:

> _Contradicts ADR-0007 (event-sourced orders) — but worth reopening because…_
`;
}

/** The three files as `init` plans expect them: `[path, content]`. */
export function agentsDocs(tracker) {
  return [
    ['docs/agents/issue-tracker.md', renderIssueTrackerDoc(tracker)],
    ['docs/agents/triage-labels.md', renderTriageLabelsDoc()],
    ['docs/agents/domain.md', renderDomainDoc()],
  ];
}
