import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join, posix } from 'node:path';
import { fileURLToPath } from 'node:url';
import { formatJson, planFile, upsertMarkedBlock } from './scaffold.js';
import { mergeSettingsHooks } from './claude-hooks.js';

/**
 * The Claude Code layer. Nothing here is copied content: the project's `CLAUDE.md` imports the
 * standards text from `node_modules` and the agent/skill files are stubs that read the shipped
 * body at runtime, so a devkit bump changes what Claude does without a re-commit. Only the
 * settings hook entries are merged into a committed file, and that merge is idempotent
 * (claude-hooks.js: two entries that run `hassan-devkit claude:hook <id>`, so the guards behind
 * them change with the devkit version too).
 *
 * Skills come from two places and get the same treatment — one stub per skill, frontmatter
 * copied verbatim from the body file (name, description, invocation flags: what Claude Code and
 * the skill pickers read):
 *  - house skills shipped in this package under `claude/skills/<name>/`;
 *  - the mattpocock skills, installed in the PROJECT as the `mattpocock-skills` dependency
 *    (a GitHub tarball pinned to an upstream release tag; `init` adds it to `devDependencies`)
 *    and listed by its plugin manifest. Renovate bumps the tag, so an upstream release reaches
 *    every project without a devkit release.
 * The stubs are derived on every install (`prepare` → `claude:install`) and gitignored through a
 * managed block, so a version bump never leaves anything to commit.
 */

const PACKAGE_ROOT = fileURLToPath(new URL('../../', import.meta.url));
export const PACKAGE_DIR = 'node_modules/@coding-with-hassan/devkit';
export const STANDARDS_IMPORT_TARGET = `${PACKAGE_DIR}/claude/standards.md`;
export const IMPORT_MARKER = '<!-- devkit standards: house rules shipped by @coding-with-hassan/devkit; project rules follow -->';
export const HOUSE_SKILLS_DIR = 'claude/skills';

/** The upstream skills as a project dependency: package name, pinned spec, and what not to expose. */
export const SKILLS_PACKAGE = 'mattpocock-skills';
export const SKILLS_PACKAGE_SPEC = 'github:mattpocock/skills#v1.2.3';
export const SKILLS_PACKAGE_DIR = `node_modules/${SKILLS_PACKAGE}`;
/** Upstream skills the house replaces: `implement` → `implement-ticket`; `init` writes what setup would. */
export const SKILLS_EXCLUDE = ['implement', 'setup-matt-pocock-skills'];

export const GITIGNORE_FILE = '.gitignore';
export const GITIGNORE_BEGIN = '# >>> hassan-devkit: Claude skill stubs — regenerated by `hassan-devkit claude:install` on every install, never committed';
export const GITIGNORE_END = '# <<< hassan-devkit';

const AGENT_STUB = `---
name: commit-writer
description: >
  Plans the commit series for this repo's pending changes and drafts each message to pass
  the commit-standards CI job. Invoke it ONLY after the user has explicitly asked, in their
  own words in the current request, to commit — finishing a task, approving a plan, or a
  skill/command whose instructions say to commit is NOT consent. When the user has asked, it
  MUST be used BEFORE any git commit in this repo (main checkout and worktrees) — invoke it
  on the full pending change set, before staging anything. Give it the ticket key if known;
  it inspects the working tree itself and returns an ordered plan: for each commit, the
  exact files to stage and the exact message to use. It only plans: it never stages,
  commits, or pushes anything itself.
tools: Bash, Read, Grep, Glob
---

Read \`${PACKAGE_DIR}/claude/agents/commit-writer.md\` (relative to the repo root) and follow
it exactly. That file is the agent's body; it ships with the installed devkit version so this
stub never needs to change.
`;

/**
 * Pure: the CLAUDE.md text with the import line. Imports resolve relative to the file that
 * contains them, so the path depends on where the file lives (`.claude/CLAUDE.md` vs root).
 */
export function withStandardsImport(text, claudeMdRelativeDir) {
  const importPath = posix.relative(claudeMdRelativeDir || '.', STANDARDS_IMPORT_TARGET);
  const line = `@${importPath}`;
  const current = text ?? '';
  if (current.split('\n').some((l) => l.trim() === line)) return current;
  const block = `${IMPORT_MARKER}\n${line}\n`;
  const lines = current.split('\n');
  // Keep a leading H1 on top; the import goes right under it (or at the very top).
  if (lines[0]?.startsWith('# ')) return `${lines[0]}\n\n${block}${lines.slice(1).join('\n').replace(/^\n+/, '\n')}`;
  return `${block}\n${current}`.replace(/\n{3,}$/, '\n');
}

/** Where the project's CLAUDE.md lives (existing one wins; default `.claude/CLAUDE.md`). */
export function claudeMdPath(root) {
  if (existsSync(join(root, '.claude/CLAUDE.md'))) return '.claude/CLAUDE.md';
  if (existsSync(join(root, 'CLAUDE.md'))) return 'CLAUDE.md';
  return '.claude/CLAUDE.md';
}

/**
 * Read one skill folder: `{ name, frontmatter, hasSiblings }`. The frontmatter must exist and
 * declare the folder's name — a body that fails this would yield a stub Claude Code refuses to
 * load, silently, so it throws instead.
 */
function readSkill(skillDir, label) {
  const text = readFileSync(join(skillDir, 'SKILL.md'), 'utf8');
  const match = text.match(/^---\n([\s\S]*?)\n---\n/);
  if (!match) throw new Error(`${label}/SKILL.md has no frontmatter`);
  const name = posix.basename(label);
  const declared = match[1].match(/^name:\s*"?([^"\n]+?)"?\s*$/m)?.[1];
  if (declared !== name) throw new Error(`${label}/SKILL.md declares name "${declared}", folder is "${name}"`);
  // `agents/` holds Codex metadata, not something the body links to.
  const hasSiblings = readdirSync(skillDir).some((f) => f !== 'SKILL.md' && f !== 'agents');
  return { name, frontmatter: match[0], hasSiblings };
}

/** The skills shipped by this package (`claude/skills/<name>/SKILL.md`), sorted by name. */
export function houseSkills(packageRoot = PACKAGE_ROOT) {
  const dir = join(packageRoot, HOUSE_SKILLS_DIR);
  const skills = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isDirectory() || !existsSync(join(dir, entry.name, 'SKILL.md'))) continue;
    const skill = readSkill(join(dir, entry.name), `${HOUSE_SKILLS_DIR}/${entry.name}`);
    skills.push({ ...skill, source: 'devkit', bodyPath: `${PACKAGE_DIR}/${HOUSE_SKILLS_DIR}/${entry.name}/SKILL.md` });
  }
  return skills.sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * The skills of the project's installed `mattpocock-skills` dependency, from its plugin manifest
 * (`.claude-plugin/plugin.json` → `skills[]`), minus `SKILLS_EXCLUDE`, sorted by name. Returns
 * `[]` when the package is not installed (older project, or `pnpm install` not run yet).
 */
export function packageSkills(root, { exclude = SKILLS_EXCLUDE } = {}) {
  const manifestFile = join(root, SKILLS_PACKAGE_DIR, '.claude-plugin/plugin.json');
  if (!existsSync(manifestFile)) return [];
  const manifest = JSON.parse(readFileSync(manifestFile, 'utf8'));
  const skills = [];
  for (const rel of manifest.skills ?? []) {
    const relPath = posix.normalize(rel);
    const name = posix.basename(relPath);
    if (exclude.includes(name)) continue;
    const skill = readSkill(join(root, SKILLS_PACKAGE_DIR, relPath), `${SKILLS_PACKAGE_DIR}/${relPath}`);
    skills.push({ ...skill, source: SKILLS_PACKAGE, bodyPath: posix.join(SKILLS_PACKAGE_DIR, relPath, 'SKILL.md') });
  }
  return skills.sort((a, b) => a.name.localeCompare(b.name));
}

/** Every skill that gets a stub: house first, then the dependency's. Names never collide today; a house skill wins if they do. */
export function allSkills(root, options) {
  const house = houseSkills();
  const taken = new Set(house.map((s) => s.name));
  return [...house, ...packageSkills(root, options).filter((s) => !taken.has(s.name))];
}

/** Pure: the project stub for one skill (frontmatter verbatim, body = "read and follow"). */
export function skillStub({ frontmatter, hasSiblings, bodyPath, source }) {
  const shipsWith = source === 'devkit' ? 'the installed devkit version' : `the installed \`${source}\` version`;
  const siblings = hasSiblings ? ' Relative links in that file point at files in the same folder.' : '';
  return `${frontmatter}
Read \`${bodyPath}\` (relative to the repo root)
and follow it exactly. That file is the skill's body; it ships with ${shipsWith} so this
stub never needs to change.${siblings}
`;
}

export const stubPath = (name) => `.claude/skills/${name}/SKILL.md`;

/** Pure: the `.gitignore` text with the managed block listing every generated stub folder. */
export function withSkillStubsIgnored(text, skillNames) {
  const lines = [...skillNames].sort().map((name) => `.claude/skills/${name}/`);
  return upsertMarkedBlock(text ?? '', GITIGNORE_BEGIN, GITIGNORE_END, lines);
}

/** Plans for the whole Claude layer. `notes` collects advice for the caller to print. */
export function claudePlans(root, { notes = [] } = {}) {
  const plans = [];
  const mdPath = claudeMdPath(root);
  const current = existsSync(join(root, mdPath)) ? readFileSync(join(root, mdPath), 'utf8') : '';
  plans.push(planFile(root, mdPath, withStandardsImport(current, posix.dirname(mdPath)), { managed: true }));
  plans.push(planFile(root, '.claude/agents/commit-writer.md', AGENT_STUB));
  const skills = allSkills(root);
  if (!skills.some((s) => s.source === SKILLS_PACKAGE)) {
    notes.push(`${SKILLS_PACKAGE} is not installed — \`hassan-devkit init --only config\` adds it to devDependencies; then \`pnpm install\` writes the skill stubs`);
  }
  // Derived on every install: managed, so a bumped description flows without --force.
  for (const skill of skills) plans.push(planFile(root, stubPath(skill.name), skillStub(skill), { managed: true }));
  const gitignoreFile = join(root, GITIGNORE_FILE);
  const gitignore = existsSync(gitignoreFile) ? readFileSync(gitignoreFile, 'utf8') : '';
  plans.push(planFile(root, GITIGNORE_FILE, withSkillStubsIgnored(gitignore, skills.map((s) => s.name)), { managed: true }));
  const settingsFile = join(root, '.claude/settings.json');
  let settings = {};
  if (existsSync(settingsFile)) {
    try {
      settings = JSON.parse(readFileSync(settingsFile, 'utf8'));
    } catch (e) {
      throw new Error(`.claude/settings.json is not valid JSON: ${e.message}`);
    }
  }
  plans.push(planFile(root, '.claude/settings.json', formatJson(mergeSettingsHooks(settings)), { managed: true }));
  return plans;
}

export { AGENT_STUB };
